// types/admin/FSM/mockStore.ts (or any shared utils folder)
import { Contribution } from "./contribution-rules";

export const sharedMockDataset: Contribution[] = [
  {
    id: "VOC-KNG-001",
    contributor_id: "usr_contrib_12",
    contributor_name: "Jasper Bruhl",
    dialect: "Kangri",
    word_devanagari: "पहाड़",
    meaning:
      "पर्वत, ऊँचा भूभाग। विशाल प्राकृतिक संरचना जो आस-पास की भूमि से काफी ऊँची होती है।",
    example_sentence: "तुसां पहाड़ कजो जांदे दे?",
    region: "Palampur",
    category: "Nature & Geography",
    word_latin: "pahāṛ",
    ipa: "pəɦaːɽ",
    meaning_hindi: "पर्वत",
    meaning_english: "Mountain",
    example_sentence_english: "Why are you going to the mountains?",
    example_sentence_hindi: "आप पहाड़ क्यों जा रहे हैं?",
    status: "pending_review_1",
    level1_reviewer_id: null,
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-24T10:30:00.000Z",
    updated_at: "2026-06-24T10:30:00.000Z",
  },
  {
    id: "VOC-MND-002",
    contributor_id: "usr_contrib_13",
    contributor_name: "MandiCulture",
    dialect: "Mandyali",
    word_devanagari: "ओतड़",
    meaning:
      "ऐसी भूमि जहाँ सिंचाई की सुविधा न हो, पूरी तरह वर्षा पर निर्भर सूखी ज़मीन।",
    example_sentence: "एतकी ओतड़ा री ज़मीना च कनक नी होई।",
    region: "Sunder Nagar",
    category: "Agriculture & Land",
    word_latin: "otaṛ",
    ipa: "oːt̪əɽ",
    meaning_hindi: "असिंचित भूमि",
    meaning_english: "Unirrigated dry land",
    example_sentence_english:
      "This year wheat didn't grow well in the unirrigated land.",
    example_sentence_hindi: "इस साल असिंचित भूमि में गेहूं नहीं हुआ।",
    status: "pending_review_1",
    level1_reviewer_id: null,
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-24T11:15:00.000Z",
    updated_at: "2026-06-24T11:15:00.000Z",
  },
  {
    id: "VOC-KUL-003",
    contributor_id: "usr_contrib_14",
    contributor_name: "KulluValleyVoice",
    dialect: "Kulluvi",
    word_devanagari: "काउणी",
    meaning:
      "एक प्रकार का पहाड़ी बारीक अनाज (फॉक्सटेल मिलेट) जो सेहत के लिए पौष्टिक होता है।",
    example_sentence: "काउणी री खीर बड़ी सवादू हुंदी।",
    region: "Manali",
    category: "Food & Culinary",
    word_latin: "kāuṇī",
    ipa: "kaːuɳiː",
    meaning_hindi: "कंगनी (अनाज)",
    meaning_english: "Foxtail Millet",
    example_sentence_english:
      "The pudding made of foxtail millet is very delicious.",
    example_sentence_hindi: "कंगनी की खीर बहुत स्वादिष्ट होती है।",
    status: "pending_review_1",
    level1_reviewer_id: null,
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-24T14:20:00.000Z",
    updated_at: "2026-06-24T14:20:00.000Z",
  },
  {
    id: "VOC-CHM-004",
    contributor_id: "usr_contrib_15",
    contributor_name: "ChambaRavi",
    dialect: "Chameali",
    word_devanagari: "हंज",
    meaning:
      "आँख से निकलने वाले आँसू; दुःख या अत्यधिक हर्ष के समय निकलने वाला जल।",
    example_sentence: "तेरी अक्खी च हंज कजो आए?",
    region: "Bharmour",
    category: "Human Emotions",
    word_latin: "hañj",
    ipa: "ɦəɲɟ",
    meaning_hindi: "आँसू",
    meaning_english: "Tears",
    example_sentence_english: "Why did tears come into your eyes?",
    example_sentence_hindi: "तुम्हारी आँख में आँसू क्यों आए?",
    status: "pending_review_1",
    level1_reviewer_id: null,
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-24T16:05:00.000Z",
    updated_at: "2026-06-24T16:05:00.000Z",
  },
  {
    id: "VOC-KNG-005",
    contributor_id: "usr_contrib_16",
    contributor_name: "DhauladharRider",
    dialect: "Kangri",
    word_devanagari: "द्रमड़",
    meaning:
      "मिट्टी का ढेला या खेत की जुताई के बाद बचे हुए मिट्टी के कड़े टुकड़े।",
    example_sentence: "खेत च द्रमड़ भंने पउणे।",
    region: "Dharamshala",
    category: "Agriculture & Land",
    word_latin: "dramaṛ",
    ipa: "d̪ɾəməɽ",
    meaning_hindi: "मिट्टी का ढेला",
    meaning_english: "Clod of earth",
    example_sentence_english: "We need to break the soil clods in the field.",
    example_sentence_hindi: "खेत में मिट्टी के ढेले तोड़ने पड़ेंगे।",
    status: "pending_review_2",
    level1_reviewer_id: "usr_expert_77",
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-24T17:45:00.000Z",
    updated_at: "2026-06-24T19:00:00.000Z",
  },
  {
    id: "VOC-KIN-006",
    contributor_id: "usr_contrib_17",
    contributor_name: "KinnaurTribal",
    dialect: "Kinnauri",
    word_devanagari: "रिंगपा",
    meaning: "बुद्धिमान, चतुर या गहरी समझ रखने वाला व्यक्ति।",
    example_sentence: "एश मती रिंगपा मीश बा।",
    region: "Kalpa",
    category: "Human Characteristics",
    word_latin: "ringpā",
    ipa: "ɾiŋpaː",
    meaning_hindi: "बुद्धिमान",
    meaning_english: "Intelligent / Wise",
    example_sentence_english: "This boy is very intelligent.",
    example_sentence_hindi: "यह लड़का बहुत बुद्धिमान है।",
    status: "pending_review_1",
    level1_reviewer_id: null,
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-25T08:10:00.000Z",
    updated_at: "2026-06-25T08:10:00.000Z",
  },
  {
    id: "VOC-SIR-007",
    contributor_id: "usr_contrib_18",
    contributor_name: "SirmauriGiri",
    dialect: "Sirmauri",
    word_devanagari: "झाकड़ी",
    meaning:
      "मिट्टी का छोटा बर्तन जिसका उपयोग छाछ या दही रखने के लिए किया जाता है।",
    example_sentence: "झाकड़िया दी छाछ ठंडी रहंदी।",
    region: "Nahan",
    category: "Household Objects",
    word_latin: "jhākaṛī",
    ipa: "ɟʱaːkəɽiː",
    meaning_hindi: "कुल्हड़ / मटकी",
    meaning_english: "Small earthen pot",
    example_sentence_english:
      "Buttermilk remains cold in the small earthen pot.",
    example_sentence_hindi: "मटकी में छाछ ठंडी रहती है।",
    status: "questionable",
    level1_reviewer_id: null,
    level2_reviewer_id: null,
    questionable_by: "Jasper Dahl",
    questionable_reason:
      "कृपया इसके लिए सटीक आईपीए (IPA) प्रोनंसिएशन की जांच करें, यह कुछ अशुद्ध लग रहा है।",
    created_at: "2026-06-25T09:30:00.000Z",
    updated_at: "2026-06-25T11:20:00.000Z",
  },
  {
    id: "VOC-KNG-008",
    contributor_id: "usr_contrib_12",
    contributor_name: "HimachalPreserver",
    dialect: "Kangri",
    word_devanagari: "चेतड़िया",
    meaning:
      "चतुर, चालाक या बहुत सतर्क रहने वाली चिड़िया या व्यक्ति के संदर्भ में व्यापक लोक शब्द।",
    example_sentence: "बड़ा चतेड़िया मानु है ओ।",
    region: "Kangra",
    category: "Human Characteristics",
    word_latin: "chetaṛiyā",
    ipa: "tʃeːt̪əɽijaː",
    meaning_hindi: "चालाक / सतर्क",
    meaning_english: "Clever / Cunning",
    example_sentence_english: "He is a very clever man.",
    example_sentence_hindi: "वह बहुत चालाक आदमी है।",
    status: "pending_review_1",
    level1_reviewer_id: null,
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-25T10:00:00.000Z",
    updated_at: "2026-06-25T10:00:00.000Z",
  },
  {
    id: "VOC-MND-009",
    contributor_id: "usr_contrib_13",
    contributor_name: "MandiCulture",
    dialect: "Mandyali",
    word_devanagari: "गाम",
    meaning:
      "धूप; सूरज की गर्मी जो कड़े जाड़े के दिनों में पहाड़ी ढलानों पर सुखद लगती है।",
    example_sentence: "चला बहरी गामा च बअते।",
    region: "Joginder Nagar",
    category: "Nature & Geography",
    word_latin: "gām",
    ipa: "ɡaːm",
    meaning_hindi: "धूप",
    meaning_english: "Sunshine / Sunlight",
    example_sentence_english: "Come, let's sit outside in the sunshine.",
    example_sentence_hindi: "चलो बाहर धूप में बैठते हैं।",
    status: "pending_review_2",
    level1_reviewer_id: "usr_expert_77",
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-25T10:15:00.000Z",
    updated_at: "2026-06-25T13:00:00.000Z",
  },
  {
    id: "VOC-KUL-010",
    contributor_id: "usr_contrib_14",
    contributor_name: "KulluValleyVoice",
    dialect: "Kulluvi",
    word_devanagari: "थतलू",
    meaning:
      "लकड़ी या पत्थर का बना छोटा ढांचा या चबूतरा जिसपर बैठकर ग्रामीण बातचीत करते हैं।",
    example_sentence: "बुजुर्ग थतलुआ पर बैठे थे।",
    region: "Naggar",
    category: "Household Objects",
    word_latin: "thatlū",
    ipa: "t̪ʰət̪luː",
    meaning_hindi: "चबूतरा",
    meaning_english: "Small stone platform",
    example_sentence_english: "The elders were sitting on the stone platform.",
    example_sentence_hindi: "बुजुर्ग चबूतरे पर बैठे थे।",
    status: "pending_review_1",
    level1_reviewer_id: null,
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-25T11:00:00.000Z",
    updated_at: "2026-06-25T11:00:00.000Z",
  },
  {
    id: "VOC-CHM-011",
    contributor_id: "usr_contrib_15",
    contributor_name: "ChambaRavi",
    dialect: "Chameali",
    word_devanagari: "ज्वाल",
    meaning: "खेतों के बीच का तंग और संकरा रास्ता; पगडंडी।",
    example_sentence: "इस ज्वाला लांगे गामे दा रस्ता है।",
    region: "Chamba Town",
    category: "Nature & Geography",
    word_latin: "jvāl",
    ipa: "ɟʋaːl",
    meaning_hindi: "पगडंडी / संकरा रास्ता",
    meaning_english: "Narrow field path",
    example_sentence_english:
      "The way to the village goes through this narrow field path.",
    example_sentence_hindi: "गाँव का रास्ता इस पगडंडी से होकर जाता है।",
    status: "pending_review_1",
    level1_reviewer_id: null,
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-25T11:40:00.000Z",
    updated_at: "2026-06-25T11:40:00.000Z",
  },
  {
    id: "VOC-LAH-012",
    contributor_id: "usr_contrib_20",
    contributor_name: "LahaulSnow",
    dialect: "Lahauli",
    word_devanagari: "ख्यांग",
    meaning:
      "जंगली गधा जो तिब्बती पठार और लाहौल-स्पीति के उच्च पर्वतीय मैदानों में पाया जाता है।",
    example_sentence: "स्पीति दी घाटी च ख्यांग दिखे।",
    region: "Kaza",
    category: "Animals & Wildlife",
    word_latin: "khyāṅg",
    ipa: "kʰjaːŋ",
    meaning_hindi: "जंगली गधा (कियांग)",
    meaning_english: "Tibetan Wild Ass",
    example_sentence_english: "Wild asses were spotted in the Spiti valley.",
    example_sentence_hindi: "स्पीति की घाटी में जंगली गधे देखे गए।",
    status: "pending_review_1",
    level1_reviewer_id: null,
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-25T12:10:00.000Z",
    updated_at: "2026-06-25T12:10:00.000Z",
  },
  {
    id: "VOC-KNG-013",
    contributor_id: "usr_contrib_16",
    contributor_name: "DhauladharRider",
    dialect: "Kangri",
    word_devanagari: "धौळ",
    meaning:
      "सफेद रंग; पहाड़ों पर ताज़ा गिरी बर्फ की सफेदी या साफ धुले कपड़ों की चमक।",
    example_sentence: "धौळी धार बर्फे कन्नै ढकी गेई।",
    region: "Nurpur",
    category: "Nature & Geography",
    word_latin: "dhauḷ",
    ipa: "d̪ʱɔːɭ",
    meaning_hindi: "सफेद / श्वेत",
    meaning_english: "White / Fair",
    example_sentence_english: "The white range has been covered with snow.",
    example_sentence_hindi: "सफेद पर्वत श्रृंखला बर्फ से ढक गई है।",
    status: "pending_review_2",
    level1_reviewer_id: "usr_expert_77",
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-25T13:25:00.000Z",
    updated_at: "2026-06-25T14:10:00.000Z",
  },
  {
    id: "VOC-MND-014",
    contributor_id: "usr_contrib_13",
    contributor_name: "MandiCulture",
    dialect: "Mandyali",
    word_devanagari: "कुळथ",
    meaning:
      "कुलथी की दाल जो पहाड़ी इलाकों में सर्दियों में बहुत चाव से खाई जाती है और सेहतमंद होती है।",
    example_sentence: "सर्दियां च कुळथी री दाल खाणी चाहिदी।",
    region: "Sarkaghat",
    category: "Food & Culinary",
    word_latin: "kuḷath",
    ipa: "kul̪t̪ʰ",
    meaning_hindi: "कुलथी की दाल",
    meaning_english: "Horse gram",
    example_sentence_english:
      "One should eat horse gram lentil during winters.",
    example_sentence_hindi: "सर्दियों में कुलथी की दाल खानी चाहिए।",
    status: "pending_review_1",
    level1_reviewer_id: null,
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-25T14:00:00.000Z",
    updated_at: "2026-06-25T14:00:00.000Z",
  },
  {
    id: "VOC-SIR-015",
    contributor_id: "usr_contrib_18",
    contributor_name: "SirmauriGiri",
    dialect: "Sirmauri",
    word_devanagari: "खेल्टा",
    meaning:
      "बांस की खपच्चियों से बुनी बड़ी टोकरी जिसका उपयोग घास या सेब ढोने में किया जाता है।",
    example_sentence: "ओह खेल्टा भरी करी घास लेया।",
    region: "Rajgarh",
    category: "Household Objects",
    word_latin: "khelṭā",
    ipa: "kʰeːlʈaː",
    meaning_hindi: "बड़ी टोकरी (किल्टा)",
    meaning_english: "Large bamboo basket",
    example_sentence_english:
      "He brought grass filling up the large bamboo basket.",
    example_sentence_hindi: "वह बड़ी टोकरी भरकर घास लाया।",
    status: "pending_review_1",
    level1_reviewer_id: null,
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-25T15:15:00.000Z",
    updated_at: "2026-06-25T15:15:00.000Z",
  },
  {
    id: "VOC-KUL-016",
    contributor_id: "usr_contrib_14",
    contributor_name: "KulluValleyVoice",
    dialect: "Kulluvi",
    word_devanagari: "पट्टू",
    meaning:
      "भेड़ की ऊन से हाथ द्वारा बुना जाने वाला भारी और गर्म पारंपरिक पहाड़ी शॉल या वस्त्र।",
    example_sentence: "एतकी मांए नया पट्टू बुणिया।",
    region: "Kullu Town",
    category: "Clothing & Attire",
    word_latin: "paṭṭū",
    ipa: "pəʈːuː",
    meaning_hindi: "पट्टू (ऊनी वस्त्र)",
    meaning_english: "Traditional woolen shawl",
    example_sentence_english: "This year mother wove a new woolen shawl.",
    example_sentence_hindi: "इस साल माँ ने नया पट्टू बुना।",
    status: "pending_review_2",
    level1_reviewer_id: "usr_expert_77",
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-25T16:20:00.000Z",
    updated_at: "2026-06-25T17:30:00.000Z",
  },
  {
    id: "VOC-KIN-017",
    contributor_id: "usr_contrib_17",
    contributor_name: "KinnaurTribal",
    dialect: "Kinnauri",
    word_devanagari: "शोंग",
    meaning: "पहाड़ी इलाक़े में बहने वाली तीव्र वेग की नदी या जलधारा।",
    example_sentence: "शोंगा दा पाणी मती ठंडा बा।",
    region: "Sangla",
    category: "Nature & Geography",
    word_latin: "śoṅg",
    ipa: "ʃoŋ",
    meaning_hindi: "नदी / जलधारा",
    meaning_english: "River stream",
    example_sentence_english: "The water of the river stream is very cold.",
    example_sentence_hindi: "जलधारा का पानी बहुत ठंडा है।",
    status: "pending_review_1",
    level1_reviewer_id: null,
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-25T17:05:00.000Z",
    updated_at: "2026-06-25T17:05:00.000Z",
  },
  {
    id: "VOC-CHM-018",
    contributor_id: "usr_contrib_15",
    contributor_name: "ChambaRavi",
    dialect: "Chameali",
    word_devanagari: "घराट",
    meaning: "पानी के वेग से चलने वाली पारंपरिक पहाड़ी आटा चक्की (पनचक्की)।",
    example_sentence: "घराटा दा पीठा सवादू हुंदा।",
    region: "Chamba Town",
    category: "Household Objects",
    word_latin: "gharāṭ",
    ipa: "ɡʱəɾaːʈ",
    meaning_hindi: "पनचक्की",
    meaning_english: "Watermill",
    example_sentence_english: "Flour ground in the watermill is tastier.",
    example_sentence_hindi: "पनचक्की का पिसा हुआ आटा स्वादिष्ट होता है।",
    status: "pending_review_1",
    level1_reviewer_id: null,
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-25T18:30:00.000Z",
    updated_at: "2026-06-25T18:30:00.000Z",
  },
  {
    id: "VOC-KNG-019",
    contributor_id: "usr_contrib_12",
    contributor_name: "HimachalPreserver",
    dialect: "Kangri",
    word_devanagari: "द्रट",
    meaning:
      "तेज़ धार वाला दरांती जैसा औज़ार जिसका उपयोग झाड़ियां या घास काटने के लिए किया जाता है।",
    example_sentence: "द्रट कन्नै झाड़ियां कटी दित्तियां।",
    region: "Dehra",
    category: "Household Objects",
    word_latin: "draṭ",
    ipa: "d̪ɾəʈ",
    meaning_hindi: "दरांती / दाट",
    meaning_english: "Sickle / Billhook tool",
    example_sentence_english:
      "The bushes were cleared using the billhook tool.",
    example_sentence_hindi: "दरांती से झाड़ियाँ काट दी गईं।",
    status: "pending_review_1",
    level1_reviewer_id: null,
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-25T19:00:00.000Z",
    updated_at: "2026-06-25T19:00:00.000Z",
  },
  {
    id: "VOC-SIR-020",
    contributor_id: "usr_contrib_18",
    contributor_name: "SirmauriGiri",
    dialect: "Sirmauri",
    word_devanagari: "नाटी",
    meaning:
      "पारंपरिक पहाड़ी लोक नृत्य जो त्योहारों, मेलों और शादियों में सामूहिक रूप से किया जाता है।",
    example_sentence: "सारे मेले च नाटी पाए रहे थे।",
    region: "Paonta Sahib",
    category: "Arts & Culture",
    word_latin: "nāṭī",
    ipa: "naːʈiː",
    meaning_hindi: "नाटी (लोक नृत्य)",
    meaning_english: "Traditional folklore dance",
    example_sentence_english: "Everyone was dancing Nati in the fair.",
    example_sentence_hindi: "सभी मेले में नाटी नृत्य कर रहे थे।",
    status: "pending_review_1",
    level1_reviewer_id: null,
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-25T20:10:00.000Z",
    updated_at: "2026-06-25T20:10:00.000Z",
  },
  {
    id: "VOC-MND-021",
    contributor_id: "usr_contrib_13",
    contributor_name: "MandiCulture",
    dialect: "Mandyali",
    word_devanagari: "बथाण",
    meaning:
      "पहाड़ी खेतों में मवेशियों (गायों/बैलों) को अस्थायी रूप से बांधने या रखने का बाड़ा या स्थान।",
    example_sentence: "ढोर बथाणे च बन्धी देओ।",
    region: "Karsog",
    category: "Agriculture & Land",
    word_latin: "bathāṇ",
    ipa: "bət̪ʰaːɳ",
    meaning_hindi: "पशुओं का बाड़ा",
    meaning_english: "Cattle enclosure field",
    example_sentence_english: "Tie the cattle inside the enclosure.",
    example_sentence_hindi: "मवेशियों को बाड़े में बाँध दो।",
    status: "pending_review_1",
    level1_reviewer_id: null,
    level2_reviewer_id: null,
    questionable_by: null,
    questionable_reason: null,
    created_at: "2026-06-25T21:15:00.000Z",
    updated_at: "2026-06-25T21:15:00.000Z",
  },
];
